system:
    admin_group:
        admin_ui_forms:
            content_edit_form_templates:
                - { template: '@ezdesign/content/imagemap_form_fields.html.twig', priority: 1 }

        field_templates:
            - { template: '@ezdesign/fields/imagemap_content_fields.html.twig', priority: 0 }
