services:
    Onisep\ImageMapBundle\FieldType\ImageMap\Type:
        parent: ezpublish.fieldType
        tags:
            - { name: ezplatform.field_type, alias: imagemap }

    Onisep\ImageMapBundle\FieldType\ImageMap\Storage:
        arguments:
            - '@ezpublish.fieldType.ezimage.storage_gateway'
            - '@ezpublish.fieldType.ezimage.io_service'
            - '@ezpublish.fieldType.ezimage.pathGenerator'
            - '@ezpublish.fieldType.metadataHandler.imagesize'
            - '@ezpublish.utils.deprecation_warner'
            - '@Onisep\ImageMapBundle\FieldType\ImageMap\ImageMapStorage\Gateway\LegacyStorage'
            - '@?ezpublish.image_alias.imagine.alias_cleaner'
            - '@eZ\Publish\Core\IO\FilePathNormalizerInterface'
        tags:
            - { name: ezplatform.field_type.external_storage_handler, alias: imagemap }

    Onisep\ImageMapBundle\FieldType\ImageMap\FieldValueConverter:
        arguments:
            - '@ezpublish.fieldType.ezimage.io_service'
            - '@ezpublish.core.io.image_fieldtype.legacy_url_redecorator'
        tags:
            - { name: ezplatform.field_type.legacy_storage.converter, alias: imagemap, lazy: true, callback: '::create' }

    Onisep\ImageMapBundle\FieldType\ImageMap\ImageMapStorage\Gateway\LegacyStorage:
        arguments: ['@Onisep\ImageMapBundle\Database\ImageMapRepository']
        tags:
            - { name: ezplatform.field_type.external_storage_handler.gateway, alias: imagemap, identifier: LegacyStorage }

    Onisep\ImageMapBundle\Database\ImageMapRepository:
        arguments: ['@ezpublish.persistence.connection']
