services:
    Onisep\IbexaImageMapBundle\FieldType\ImageMap\Type:
        arguments:
            - ['@ezpublish.fieldType.validator.black_list', '@ezpublish.fieldType.validator.image']
        parent: ezpublish.fieldType
        tags:
            - { name: ezpublish.fieldType, alias: imagemap }

    Onisep\IbexaImageMapBundle\FieldType\ImageMap\Storage:
        arguments:
            - '@ezpublish.fieldType.ezimage.storage_gateway'
            - '@ezpublish.fieldType.ezimage.io_service'
            - '@ezpublish.fieldType.ezimage.pathGenerator'
            - '@ezpublish.fieldType.metadataHandler.imagesize'
            - '@ezpublish.utils.deprecation_warner'
            - '@Onisep\IbexaImageMapBundle\FieldType\ImageMap\ImageMapStorage\Gateway\LegacyStorage'
            - '@?ezpublish.image_alias.imagine.alias_cleaner'
            - '@eZ\Publish\Core\IO\FilePathNormalizerInterface'
        tags:
            - { name: ezpublish.fieldType.externalStorageHandler, alias: imagemap }

    Onisep\IbexaImageMapBundle\FieldType\ImageMap\FieldValueConverter:
        arguments:
            - '@ezpublish.fieldType.ezimage.io_service'
            - '@ezpublish.core.io.image_fieldtype.legacy_url_redecorator'
        tags:
            - { name: ezpublish.storageEngine.legacy.converter, alias: imagemap, lazy: true, callback: '::create' }

    Onisep\IbexaImageMapBundle\FieldType\ImageMap\ImageMapStorage\Gateway\LegacyStorage:
        arguments: ['@Onisep\IbexaImageMapBundle\Database\ImageMapRepository']

    Onisep\IbexaImageMapBundle\Database\ImageMapRepository:
        arguments: ['@ezpublish.persistence.connection']

    Onisep\IbexaImageMapBundle\Twig\ImageMapExtension:
        tags: ['twig.extension']

    Onisep\IbexaImageMapBundle\Twig\ImageMapRuntime:
        arguments:
            $locationService: '@eZ\Publish\API\Repository\LocationService'
            $contentService: '@eZ\Publish\API\Repository\ContentService'
        tags: ['twig.runtime']

    Onisep\IbexaImageMapBundle\Form\LinkType:
        arguments:
            $contentService: '@eZ\Publish\API\Repository\ContentService'
        tags: ['form.type']

    Onisep\IbexaImageMapBundle\Form\MapAreaType:
        tags: ['form.type']

    Onisep\IbexaImageMapBundle\Form\MapAreasType:
        tags: ['form.type']

    Onisep\IbexaImageMapBundle\Form\ImageMapType:
        tags: ['form.type']

    Onisep\IbexaImageMapBundle\FormMapper\ImageMapFormMapper:
        arguments:
            $contentTypeService: '@eZ\Publish\API\Repository\ContentTypeService'
            $locationService: '@eZ\Publish\API\Repository\LocationService'
            $fieldTypeService: '@eZ\Publish\API\Repository\FieldTypeService'
        tags:
            - { name: ez.fieldFormMapper.definition, fieldType: imagemap }
            - { name: ez.fieldFormMapper.value, fieldType: imagemap }

    Onisep\IbexaImageMapBundle\Command\SchemaCommand:
        arguments:
            $connection: '@ezpublish.persistence.connection'
        tags: ['console.command']

    onisep.imagemap.unindexed:
        class: eZ\Publish\Core\FieldType\Unindexed
        tags:
            - { name: ezpublish.fieldType.indexable, alias: imagemap }
