services:
    Onisep\IbexaImageMapBundle\FieldType\ImageMap\Type:
        arguments:
            - ['@ibexa.fieldType.validator.black_list', '@ibexa.fieldType.validator.image']
        parent: ibexa.fieldType
        tags:
            - { name: ibexa.field_type, alias: imagemap }

    Onisep\IbexaImageMapBundle\FieldType\ImageMap\Storage:
        arguments:
            - '@ibexa.fieldType.ezimage.storage_gateway'
            - '@ibexa.fieldType.ezimage.io_service'
            - '@ibexa.fieldType.ezimage.pathGenerator'
            - '@ibexa.fieldType.metadataHandler.imagesize'
            - '@ibexa.utils.deprecation_warner'
            - '@Onisep\IbexaImageMapBundle\FieldType\ImageMap\ImageMapStorage\Gateway\LegacyStorage'
            - '@?ibexa.image_alias.imagine.alias_cleaner'
            - '@Ibexa\Core\IO\FilePathNormalizerInterface'
        tags:
            - { name: ibexa.field_type.external_storage_handler, alias: imagemap }

    Onisep\IbexaImageMapBundle\FieldType\ImageMap\FieldValueConverter:
        arguments:
            - '@ibexa.fieldType.ezimage.io_service'
            - '@ibexa.core.io.image_fieldtype.legacy_url_redecorator'
        tags:
            - { name: ibexa.field_type.legacy_storage.converter, alias: imagemap, lazy: true, callback: '::create' }

    Onisep\IbexaImageMapBundle\FieldType\ImageMap\ImageMapStorage\Gateway\LegacyStorage:
        arguments: ['@Onisep\IbexaImageMapBundle\Database\ImageMapRepository']
        tags:
            - { name: ibexa.field_type.external_storage_handler.gateway, alias: imagemap, identifier: LegacyStorage }

    Onisep\IbexaImageMapBundle\Database\ImageMapRepository:
        arguments: ['@ibexa.persistence.connection']

    Onisep\IbexaImageMapBundle\Twig\ImageMapExtension:
        tags: ['twig.extension']

    Onisep\IbexaImageMapBundle\Twig\ImageMapRuntime:
        arguments:
            $locationService: '@Ibexa\Contracts\Core\Repository\LocationService'
            $contentService: '@Ibexa\Contracts\Core\Repository\ContentService'
        tags: ['twig.runtime']

    Onisep\IbexaImageMapBundle\Form\LinkType:
        arguments:
            $contentService: '@Ibexa\Contracts\Core\Repository\ContentService'
        tags: ['form.type']

    Onisep\IbexaImageMapBundle\Form\MapAreaType:
        tags: ['form.type']

    Onisep\IbexaImageMapBundle\Form\MapAreasType:
        tags: ['form.type']

    Onisep\IbexaImageMapBundle\Form\ImageMapType:
        tags: ['form.type']

    Onisep\IbexaImageMapBundle\FormMapper\ImageMapFormMapper:
        arguments:
            $contentTypeService: '@Ibexa\Contracts\Core\Repository\ContentTypeService'
            $locationService: '@Ibexa\Contracts\Core\Repository\LocationService'
            $fieldTypeService: '@Ibexa\Contracts\Core\Repository\FieldTypeService'
        tags:
            - { name: ibexa.field_type.form_mapper.definition, fieldType: imagemap }
            - { name: ibexa.field_type.form_mapper.value, fieldType: imagemap }

    Onisep\IbexaImageMapBundle\Command\SchemaCommand:
        arguments:
            $connection: '@ibexa.persistence.connection'
        tags: ['console.command']

    onisep.imagemap.unindexed:
        class: Ibexa\Core\FieldType\Unindexed
        tags:
            - { name: ibexa.field_type.indexable, alias: imagemap }
